import type { CoefficientWord } from '../types';

type Meaning = {
  partOfSpeech: CoefficientWord['partOfSpeech'];
  definition: string;
  synonyms?: string[];
  example?: string;
  phonetic?: string;
};

// Keep words strictly alphabetic to avoid normalization surprises in the Matrix.
const MEANINGS: Record<string, Meaning> = {
  abate: {
    partOfSpeech: 'verb',
    definition: 'to become less intense or widespread',
    synonyms: ['subside', 'diminish', 'ease'],
    example: 'The wind began to abate after sunset.',
  },
  aberrant: {
    partOfSpeech: 'adjective',
    definition: 'departing from what is normal or expected',
    synonyms: ['anomalous', 'atypical', 'deviant'],
    example: 'The scientist investigated an aberrant reading.',
  },
  abhor: {
    partOfSpeech: 'verb',
    definition: 'to hate or detest',
    synonyms: ['loathe', 'despise', 'detest'],
    example: 'She came to abhor dishonesty in any form.',
  },
  abjure: {
    partOfSpeech: 'verb',
    definition: 'to renounce or reject formally',
    synonyms: ['renounce', 'forswear', 'relinquish'],
    example: 'He publicly abjured his earlier claims.',
  },
  absolve: {
    partOfSpeech: 'verb',
    definition: 'to free from blame or responsibility',
    synonyms: ['exonerate', 'acquit', 'clear'],
    example: 'The evidence absolved her of wrongdoing.',
  },
  acumen: {
    partOfSpeech: 'noun',
    definition: 'keen insight and sound judgment',
    synonyms: ['shrewdness', 'discernment', 'astuteness'],
    example: 'Her academic acumen impressed the panel.',
  },
  adroit: {
    partOfSpeech: 'adjective',
    definition: 'skillful and quick in movement or thought',
    synonyms: ['deft', 'nimble', 'adept'],
    example: 'He gave an adroit response under pressure.',
  },
  advocate: {
    partOfSpeech: 'noun',
    definition: 'a person who publicly supports a cause',
    synonyms: ['supporter', 'champion', 'proponent'],
    example: 'She became an advocate for accessible education.',
  },
  affable: {
    partOfSpeech: 'adjective',
    definition: 'friendly, easy to talk to',
    synonyms: ['amiable', 'genial', 'cordial'],
    example: 'An affable tone made the meeting productive.',
  },
  agitate: {
    partOfSpeech: 'verb',
    definition: 'to stir up; to disturb or worry',
    synonyms: ['stir', 'upset', 'provoke'],
    example: 'The rumor began to agitate the student body.',
  },
  alacrity: {
    partOfSpeech: 'noun',
    definition: 'eager readiness and speed',
    synonyms: ['readiness', 'eagerness', 'promptness'],
    example: 'She accepted the task with alacrity.',
  },
  allege: {
    partOfSpeech: 'verb',
    definition: 'to claim without proof',
    synonyms: ['claim', 'assert', 'contend'],
    example: 'They alleged misconduct but offered no evidence.',
  },
  alleviate: {
    partOfSpeech: 'verb',
    definition: 'to make something less severe',
    synonyms: ['ease', 'relieve', 'mitigate'],
    example: 'A short break can alleviate mental fatigue.',
  },
  ambiguous: {
    partOfSpeech: 'adjective',
    definition: 'open to more than one interpretation',
    synonyms: ['unclear', 'vague', 'equivocal'],
    example: 'The prompt was ambiguous and caused confusion.',
  },
  ameliorate: {
    partOfSpeech: 'verb',
    definition: 'to make better; improve',
    synonyms: ['improve', 'enhance', 'alleviate'],
    example: 'Better feedback can ameliorate performance.',
  },
  amiable: {
    partOfSpeech: 'adjective',
    definition: 'pleasant and friendly',
    synonyms: ['affable', 'agreeable', 'genial'],
    example: 'His amiable manner set everyone at ease.',
  },
  anathema: {
    partOfSpeech: 'noun',
    definition: 'something intensely disliked or rejected',
    synonyms: ['abhorrence', 'bane', 'detestation'],
    example: 'Cheating was anathema to the instructor.',
  },
  anomaly: {
    partOfSpeech: 'noun',
    definition: 'something that deviates from what is standard',
    synonyms: ['irregularity', 'aberration', 'outlier'],
    example: 'The spike was an anomaly in an otherwise stable trend.',
  },
  antipathy: {
    partOfSpeech: 'noun',
    definition: 'a strong feeling of dislike',
    synonyms: ['aversion', 'hostility', 'dislike'],
    example: 'He felt antipathy toward empty rhetoric.',
  },
  apathy: {
    partOfSpeech: 'noun',
    definition: 'lack of interest, enthusiasm, or concern',
    synonyms: ['indifference', 'unconcern', 'listlessness'],
    example: 'Apathy can make studying feel impossible.',
  },
  appease: {
    partOfSpeech: 'verb',
    definition: 'to calm or satisfy demands',
    synonyms: ['pacify', 'placate', 'soothe'],
    example: 'They tried to appease the crowd with a quick update.',
  },
  arbitrary: {
    partOfSpeech: 'adjective',
    definition: 'based on random choice rather than reason',
    synonyms: ['capricious', 'random', 'unsupported'],
    example: 'The grading felt arbitrary to many students.',
  },
  arduous: {
    partOfSpeech: 'adjective',
    definition: 'requiring great effort; difficult',
    synonyms: ['strenuous', 'laborious', 'demanding'],
    example: 'The project was arduous but rewarding.',
  },
  artful: {
    partOfSpeech: 'adjective',
    definition: 'clever and skillful, often in a strategic way',
    synonyms: ['skillful', 'ingenious', 'cunning'],
    example: 'She wrote an artful response that addressed every point.',
  },
  ascetic: {
    partOfSpeech: 'adjective',
    definition: 'practicing strict self-discipline; very plain',
    synonyms: ['austere', 'spartan', 'self-denying'],
    example: 'He kept an ascetic schedule during exam week.',
  },
  assiduous: {
    partOfSpeech: 'adjective',
    definition: 'showing careful, persistent effort',
    synonyms: ['diligent', 'industrious', 'sedulous'],
    example: 'Assiduous practice boosted her score.',
  },
  astute: {
    partOfSpeech: 'adjective',
    definition: 'having sharp judgment and perception',
    synonyms: ['shrewd', 'perceptive', 'keen'],
    example: 'His astute comment reframed the debate.',
  },
  austere: {
    partOfSpeech: 'adjective',
    definition: 'plain and unadorned; strict or severe',
    synonyms: ['severe', 'spartan', 'stern'],
    example: 'The room was austere, with no decoration.',
  },
  avarice: {
    partOfSpeech: 'noun',
    definition: 'extreme greed for wealth',
    synonyms: ['greed', 'cupidity', 'rapacity'],
    example: 'Avarice drove him to take reckless risks.',
  },
  banal: {
    partOfSpeech: 'adjective',
    definition: 'so common it lacks originality',
    synonyms: ['trite', 'hackneyed', 'stale'],
    example: 'The essay relied on banal phrases.',
  },
  belligerent: {
    partOfSpeech: 'adjective',
    definition: 'hostile and aggressive',
    synonyms: ['combative', 'pugnacious', 'warlike'],
    example: 'A belligerent tone derailed the discussion.',
  },
  benevolent: {
    partOfSpeech: 'adjective',
    definition: 'kind and well-meaning',
    synonyms: ['kindly', 'charitable', 'generous'],
    example: 'The benevolent donor funded new scholarships.',
  },
  brevity: {
    partOfSpeech: 'noun',
    definition: 'shortness of expression or duration',
    synonyms: ['conciseness', 'succinctness', 'shortness'],
    example: 'Brevity made her explanation easier to follow.',
  },
  cacophony: {
    partOfSpeech: 'noun',
    definition: 'a harsh mixture of loud sounds',
    synonyms: ['din', 'clamor', 'racket'],
    example: 'The cafeteria was a cacophony at lunchtime.',
  },
  candor: {
    partOfSpeech: 'noun',
    definition: 'honest and straightforward speech',
    synonyms: ['frankness', 'openness', 'sincerity'],
    example: 'He spoke with candor about the risks.',
  },
  capricious: {
    partOfSpeech: 'adjective',
    definition: 'changing suddenly; unpredictable',
    synonyms: ['impulsive', 'fickle', 'whimsical'],
    example: 'Capricious weather ruined the outdoor plan.',
  },
  censure: {
    partOfSpeech: 'verb',
    definition: 'to express strong disapproval of',
    synonyms: ['condemn', 'reprimand', 'criticize'],
    example: 'The board voted to censure the official.',
  },
  circuitous: {
    partOfSpeech: 'adjective',
    definition: 'longer than the direct way; roundabout',
    synonyms: ['roundabout', 'indirect', 'winding'],
    example: 'His explanation was circuitous and hard to follow.',
  },
  coerce: {
    partOfSpeech: 'verb',
    definition: 'to persuade by force or threats',
    synonyms: ['compel', 'force', 'press'],
    example: 'They tried to coerce a confession.',
  },
  cogent: {
    partOfSpeech: 'adjective',
    definition: 'clear, logical, and convincing',
    synonyms: ['compelling', 'persuasive', 'sound'],
    example: 'She made a cogent case for the change.',
  },
  coherent: {
    partOfSpeech: 'adjective',
    definition: 'logical and consistent',
    synonyms: ['clear', 'ordered', 'consistent'],
    example: 'A coherent outline saves time while writing.',
  },
  collusion: {
    partOfSpeech: 'noun',
    definition: 'secret cooperation for an illegal or deceitful purpose',
    synonyms: ['conspiracy', 'plot', 'connivance'],
    example: 'Investigators looked for signs of collusion.',
  },
  complacent: {
    partOfSpeech: 'adjective',
    definition: 'overly satisfied; not eager to improve',
    synonyms: ['self-satisfied', 'smug', 'unconcerned'],
    example: 'Complacent studying can stall progress.',
  },
  concede: {
    partOfSpeech: 'verb',
    definition: 'to admit something is true or valid',
    synonyms: ['admit', 'grant', 'acknowledge'],
    example: 'She conceded that the argument had merit.',
  },
  concise: {
    partOfSpeech: 'adjective',
    definition: 'brief but clear and complete',
    synonyms: ['succinct', 'terse', 'compact'],
    example: 'A concise summary is easier to review.',
  },
  concur: {
    partOfSpeech: 'verb',
    definition: 'to agree; to share the same opinion',
    synonyms: ['agree', 'assent', 'approve'],
    example: 'Most reviewers concurred with the recommendation.',
  },
  condone: {
    partOfSpeech: 'verb',
    definition: 'to accept or allow behavior that is wrong',
    synonyms: ['tolerate', 'permit', 'overlook'],
    example: 'The policy does not condone plagiarism.',
  },
  conspicuous: {
    partOfSpeech: 'adjective',
    definition: 'easily seen or noticed',
    synonyms: ['obvious', 'noticeable', 'prominent'],
    example: 'The typo was conspicuous once you noticed it.',
  },
  constrain: {
    partOfSpeech: 'verb',
    definition: 'to limit or restrict',
    synonyms: ['restrict', 'limit', 'confine'],
    example: 'Time constraints can constrain deep work.',
  },
  contentious: {
    partOfSpeech: 'adjective',
    definition: 'likely to cause disagreement',
    synonyms: ['controversial', 'disputed', 'argumentative'],
    example: 'It was a contentious topic in the seminar.',
  },
  contend: {
    partOfSpeech: 'verb',
    definition: 'to argue or assert',
    synonyms: ['argue', 'maintain', 'claim'],
    example: 'He contended that the conclusion was premature.',
  },
  contrite: {
    partOfSpeech: 'adjective',
    definition: 'feeling remorse or guilt',
    synonyms: ['remorseful', 'repentant', 'sorry'],
    example: 'She sounded contrite after the mistake.',
  },
  copious: {
    partOfSpeech: 'adjective',
    definition: 'abundant in supply or quantity',
    synonyms: ['abundant', 'plentiful', 'ample'],
    example: 'He took copious notes during the lecture.',
  },
  corroborate: {
    partOfSpeech: 'verb',
    definition: 'to confirm with evidence',
    synonyms: ['confirm', 'support', 'substantiate'],
    example: 'The data corroborated the hypothesis.',
  },
  cursory: {
    partOfSpeech: 'adjective',
    definition: 'hasty and not thorough',
    synonyms: ['superficial', 'perfunctory', 'brief'],
    example: 'A cursory read missed the main flaw.',
  },
  daunt: {
    partOfSpeech: 'verb',
    definition: 'to intimidate or discourage',
    synonyms: ['discourage', 'deter', 'intimidate'],
    example: 'The workload did not daunt her.',
  },
  dearth: {
    partOfSpeech: 'noun',
    definition: 'a lack or shortage',
    synonyms: ['scarcity', 'shortage', 'lack'],
    example: 'There was a dearth of reliable sources.',
  },
  debunk: {
    partOfSpeech: 'verb',
    definition: 'to expose as false or exaggerated',
    synonyms: ['disprove', 'refute', 'discredit'],
    example: 'The report debunked the popular myth.',
  },
  deference: {
    partOfSpeech: 'noun',
    definition: 'respectful submission or regard',
    synonyms: ['respect', 'regard', 'courtesy'],
    example: 'Out of deference, he let her speak first.',
  },
  delineate: {
    partOfSpeech: 'verb',
    definition: 'to describe precisely; outline',
    synonyms: ['outline', 'define', 'depict'],
    example: 'The rubric delineated expectations clearly.',
  },
  demur: {
    partOfSpeech: 'verb',
    definition: 'to object or raise doubts',
    synonyms: ['object', 'protest', 'take issue'],
    example: 'She demurred when asked to change the method.',
  },
  denounce: {
    partOfSpeech: 'verb',
    definition: 'to publicly condemn',
    synonyms: ['condemn', 'decry', 'censure'],
    example: 'Leaders denounced the act as unethical.',
  },
  deplore: {
    partOfSpeech: 'verb',
    definition: 'to strongly disapprove of; lament',
    synonyms: ['lament', 'condemn', 'regret'],
    example: 'Many deplored the lack of transparency.',
  },
  deride: {
    partOfSpeech: 'verb',
    definition: 'to mock or ridicule',
    synonyms: ['mock', 'scoff', 'taunt'],
    example: 'He derided the idea instead of debating it.',
  },
  despot: {
    partOfSpeech: 'noun',
    definition: 'a ruler with absolute power',
    synonyms: ['tyrant', 'dictator', 'autocrat'],
    example: 'The despot silenced opposition quickly.',
  },
  deter: {
    partOfSpeech: 'verb',
    definition: 'to discourage from doing something',
    synonyms: ['discourage', 'prevent', 'stop'],
    example: 'Clear rules deter careless mistakes.',
  },
  diligent: {
    partOfSpeech: 'adjective',
    definition: 'showing steady, careful effort',
    synonyms: ['industrious', 'assiduous', 'careful'],
    example: 'Diligent practice beats last-minute cramming.',
  },
  disdain: {
    partOfSpeech: 'noun',
    definition: 'a feeling of contempt',
    synonyms: ['contempt', 'scorn', 'derision'],
    example: 'He spoke with disdain about the alternative.',
  },
  disparate: {
    partOfSpeech: 'adjective',
    definition: 'fundamentally different; distinct',
    synonyms: ['different', 'distinct', 'unlike'],
    example: 'The sources were disparate in style and quality.',
  },
  dispel: {
    partOfSpeech: 'verb',
    definition: 'to drive away or make disappear',
    synonyms: ['banish', 'eliminate', 'remove'],
    example: 'Practice can dispel anxiety.',
  },
  dispute: {
    partOfSpeech: 'verb',
    definition: 'to argue against; challenge',
    synonyms: ['challenge', 'contest', 'debate'],
    example: 'Experts dispute the claim.',
  },
  divulge: {
    partOfSpeech: 'verb',
    definition: 'to reveal something secret',
    synonyms: ['reveal', 'disclose', 'uncover'],
    example: 'He refused to divulge the password.',
  },
  dogmatic: {
    partOfSpeech: 'adjective',
    definition: 'asserting opinions as unquestionable facts',
    synonyms: ['opinionated', 'doctrinaire', 'rigid'],
    example: 'A dogmatic stance blocked discussion.',
  },
  dubious: {
    partOfSpeech: 'adjective',
    definition: 'doubtful; not reliable',
    synonyms: ['questionable', 'uncertain', 'suspect'],
    example: 'The evidence was dubious at best.',
  },
  eclectic: {
    partOfSpeech: 'adjective',
    definition: 'drawn from a variety of sources',
    synonyms: ['varied', 'diverse', 'wide-ranging'],
    example: 'Her eclectic reading list spanned many fields.',
  },
  efficacy: {
    partOfSpeech: 'noun',
    definition: 'the ability to produce a desired result',
    synonyms: ['effectiveness', 'power', 'success'],
    example: 'The drug’s efficacy was tested in trials.',
  },
  elicit: {
    partOfSpeech: 'verb',
    definition: 'to draw out a response',
    synonyms: ['evoke', 'prompt', 'induce'],
    example: 'The question was designed to elicit details.',
  },
  eloquent: {
    partOfSpeech: 'adjective',
    definition: 'fluent and persuasive in expression',
    synonyms: ['articulate', 'expressive', 'lucid'],
    example: 'She gave an eloquent defense of the proposal.',
  },
  elusive: {
    partOfSpeech: 'adjective',
    definition: 'difficult to find, catch, or understand',
    synonyms: ['hard-to-grasp', 'slippery', 'evasive'],
    example: 'The meaning was elusive until the final example.',
  },
  emulate: {
    partOfSpeech: 'verb',
    definition: 'to imitate in order to match or surpass',
    synonyms: ['imitate', 'copy', 'mirror'],
    example: 'He tried to emulate the clarity of great writers.',
  },
  endemic: {
    partOfSpeech: 'adjective',
    definition: 'native to a particular area; widespread in a place',
    synonyms: ['native', 'local', 'prevalent'],
    example: 'The plant is endemic to the region.',
  },
  enervate: {
    partOfSpeech: 'verb',
    definition: 'to weaken; drain energy from',
    synonyms: ['weaken', 'sap', 'exhaust'],
    example: 'All-nighters can enervate you for days.',
  },
  enigma: {
    partOfSpeech: 'noun',
    definition: 'something mysterious or hard to understand',
    synonyms: ['mystery', 'puzzle', 'riddle'],
    example: 'His motives remained an enigma.',
  },
  ephemeral: {
    partOfSpeech: 'adjective',
    definition: 'lasting a very short time',
    synonyms: ['fleeting', 'transient', 'brief'],
    example: 'The excitement was ephemeral but intense.',
  },
  equanimity: {
    partOfSpeech: 'noun',
    definition: 'calmness under stress',
    synonyms: ['composure', 'poise', 'calm'],
    example: 'She answered with equanimity despite the pressure.',
  },
  equivocal: {
    partOfSpeech: 'adjective',
    definition: 'ambiguous; not clearly decided',
    synonyms: ['ambiguous', 'uncertain', 'vague'],
    example: 'His equivocal reply avoided commitment.',
  },
  erode: {
    partOfSpeech: 'verb',
    definition: 'to wear away gradually',
    synonyms: ['wear', 'diminish', 'eat away'],
    example: 'Constant stress can erode focus.',
  },
  erudite: {
    partOfSpeech: 'adjective',
    definition: 'having great knowledge; scholarly',
    synonyms: ['learned', 'scholarly', 'well-read'],
    example: 'The erudite lecture connected many ideas.',
  },
  eschew: {
    partOfSpeech: 'verb',
    definition: 'to deliberately avoid',
    synonyms: ['avoid', 'shun', 'abstain'],
    example: 'She chose to eschew distractions during finals.',
  },
  exacerbate: {
    partOfSpeech: 'verb',
    definition: 'to make a problem worse',
    synonyms: ['worsen', 'aggravate', 'intensify'],
    example: 'Skipping sleep can exacerbate anxiety.',
  },
  exemplify: {
    partOfSpeech: 'verb',
    definition: 'to be a typical example of; illustrate',
    synonyms: ['illustrate', 'demonstrate', 'show'],
    example: 'The case exemplified the broader trend.',
  },
  exonerate: {
    partOfSpeech: 'verb',
    definition: 'to clear from blame',
    synonyms: ['absolve', 'acquit', 'clear'],
    example: 'The footage helped exonerate him.',
  },
  fastidious: {
    partOfSpeech: 'adjective',
    definition: 'very attentive to detail; hard to please',
    synonyms: ['meticulous', 'particular', 'exact'],
    example: 'A fastidious editor spotted the inconsistency.',
  },
  feasible: {
    partOfSpeech: 'adjective',
    definition: 'possible and practical to do easily',
    synonyms: ['possible', 'practical', 'workable'],
    example: 'A 10-minute routine is feasible daily.',
  },
  fervent: {
    partOfSpeech: 'adjective',
    definition: 'showing intense passion',
    synonyms: ['ardent', 'zealous', 'intense'],
    example: 'He was a fervent supporter of the program.',
  },
  flagrant: {
    partOfSpeech: 'adjective',
    definition: 'conspicuously offensive or obvious',
    synonyms: ['glaring', 'blatant', 'outrageous'],
    example: 'The error was a flagrant oversight.',
  },
  flimsy: {
    partOfSpeech: 'adjective',
    definition: 'weak and easily broken; not convincing',
    synonyms: ['weak', 'frail', 'insubstantial'],
    example: 'The argument was flimsy and unconvincing.',
  },
  foment: {
    partOfSpeech: 'verb',
    definition: 'to stir up trouble or unrest',
    synonyms: ['stir', 'incite', 'provoke'],
    example: 'The speech threatened to foment conflict.',
  },
  forbear: {
    partOfSpeech: 'verb',
    definition: 'to restrain oneself; refrain',
    synonyms: ['refrain', 'abstain', 'resist'],
    example: 'He chose to forbear from replying immediately.',
  },
  fortuitous: {
    partOfSpeech: 'adjective',
    definition: 'happening by chance, often beneficial',
    synonyms: ['lucky', 'chance', 'serendipitous'],
    example: 'A fortuitous meeting led to an internship.',
  },
  frugal: {
    partOfSpeech: 'adjective',
    definition: 'careful about spending; not wasteful',
    synonyms: ['thrifty', 'economical', 'sparing'],
    example: 'A frugal budget kept expenses under control.',
  },
  garrulous: {
    partOfSpeech: 'adjective',
    definition: 'excessively talkative',
    synonyms: ['verbose', 'chatty', 'loquacious'],
    example: 'The garrulous speaker ran over time.',
  },
  gregarious: {
    partOfSpeech: 'adjective',
    definition: 'sociable; enjoying the company of others',
    synonyms: ['outgoing', 'social', 'convivial'],
    example: 'Her gregarious nature made teamwork easy.',
  },
  guile: {
    partOfSpeech: 'noun',
    definition: 'sly or cunning intelligence',
    synonyms: ['cunning', 'craftiness', 'deceit'],
    example: 'He used guile to avoid answering directly.',
  },
  hackneyed: {
    partOfSpeech: 'adjective',
    definition: 'overused; lacking originality',
    synonyms: ['banal', 'trite', 'stale'],
    example: 'The conclusion felt hackneyed.',
  },
  hinder: {
    partOfSpeech: 'verb',
    definition: 'to make it difficult to do something',
    synonyms: ['impede', 'obstruct', 'hamper'],
    example: 'Noise can hinder concentration.',
  },
  iconoclast: {
    partOfSpeech: 'noun',
    definition: 'a person who attacks cherished beliefs',
    synonyms: ['critic', 'nonconformist', 'rebel'],
    example: 'The iconoclast challenged the standard approach.',
  },
  idiosyncrasy: {
    partOfSpeech: 'noun',
    definition: 'a distinctive personal habit or trait',
    synonyms: ['quirk', 'peculiarity', 'eccentricity'],
    example: 'His note-taking idiosyncrasy was oddly effective.',
  },
  immutable: {
    partOfSpeech: 'adjective',
    definition: 'unchanging over time',
    synonyms: ['unchangeable', 'fixed', 'constant'],
    example: 'The rules seemed immutable until revised.',
  },
  impartial: {
    partOfSpeech: 'adjective',
    definition: 'treating all sides fairly; unbiased',
    synonyms: ['unbiased', 'fair', 'neutral'],
    example: 'An impartial judge weighs evidence carefully.',
  },
  impede: {
    partOfSpeech: 'verb',
    definition: 'to hinder or obstruct',
    synonyms: ['hinder', 'obstruct', 'hamper'],
    example: 'Lack of sleep can impede learning.',
  },
  impertinent: {
    partOfSpeech: 'adjective',
    definition: 'rude; not showing proper respect',
    synonyms: ['rude', 'insolent', 'impudent'],
    example: 'The impertinent remark offended the group.',
  },
  implausible: {
    partOfSpeech: 'adjective',
    definition: 'not believable; unlikely',
    synonyms: ['unlikely', 'unconvincing', 'doubtful'],
    example: 'His excuse was implausible.',
  },
  impute: {
    partOfSpeech: 'verb',
    definition: 'to attribute something to someone',
    synonyms: ['attribute', 'ascribe', 'assign'],
    example: 'They imputed motives without evidence.',
  },
  incisive: {
    partOfSpeech: 'adjective',
    definition: 'clear and sharp in analysis',
    synonyms: ['sharp', 'penetrating', 'astute'],
    example: 'Her incisive critique improved the draft.',
  },
  inchoate: {
    partOfSpeech: 'adjective',
    definition: 'not fully formed; just beginning',
    synonyms: ['rudimentary', 'incipient', 'undeveloped'],
    example: 'The idea was inchoate but promising.',
  },
  incongruous: {
    partOfSpeech: 'adjective',
    definition: 'not in harmony; out of place',
    synonyms: ['inconsistent', 'inappropriate', 'odd'],
    example: 'His joke felt incongruous in the serious setting.',
  },
  indolent: {
    partOfSpeech: 'adjective',
    definition: 'lazy; avoiding activity',
    synonyms: ['lazy', 'slothful', 'idle'],
    example: 'An indolent routine makes progress slow.',
  },
  inherent: {
    partOfSpeech: 'adjective',
    definition: 'existing as a natural part of something',
    synonyms: ['intrinsic', 'built-in', 'essential'],
    example: 'Uncertainty is inherent in early research.',
  },
  innate: {
    partOfSpeech: 'adjective',
    definition: 'inborn; natural',
    synonyms: ['inborn', 'natural', 'intrinsic'],
    example: 'Some people have an innate sense of rhythm.',
  },
  insipid: {
    partOfSpeech: 'adjective',
    definition: 'dull; lacking flavor or interest',
    synonyms: ['dull', 'bland', 'flat'],
    example: 'The essay sounded insipid without specifics.',
  },
  intrepid: {
    partOfSpeech: 'adjective',
    definition: 'fearless; adventurous',
    synonyms: ['fearless', 'bold', 'undaunted'],
    example: 'An intrepid student tackled the hardest questions first.',
  },
  inundate: {
    partOfSpeech: 'verb',
    definition: 'to overwhelm; flood',
    synonyms: ['flood', 'overwhelm', 'swamp'],
    example: 'He was inundated with assignments.',
  },
  irreverent: {
    partOfSpeech: 'adjective',
    definition: 'showing a lack of respect',
    synonyms: ['disrespectful', 'cheeky', 'impudent'],
    example: 'An irreverent joke fell flat.',
  },
  judicious: {
    partOfSpeech: 'adjective',
    definition: 'showing good judgment; wise',
    synonyms: ['wise', 'prudent', 'sensible'],
    example: 'A judicious plan focuses on weak areas first.',
  },
  laconic: {
    partOfSpeech: 'adjective',
    definition: 'using very few words',
    synonyms: ['terse', 'brief', 'succinct'],
    example: 'His laconic reply ended the conversation.',
  },
  lament: {
    partOfSpeech: 'verb',
    definition: 'to express sorrow or regret',
    synonyms: ['mourn', 'regret', 'bemoan'],
    example: 'She lamented the lost time.',
  },
  laudable: {
    partOfSpeech: 'adjective',
    definition: 'worthy of praise',
    synonyms: ['praiseworthy', 'commendable', 'admirable'],
    example: 'Her consistency was laudable.',
  },
  lethargic: {
    partOfSpeech: 'adjective',
    definition: 'sluggish; lacking energy',
    synonyms: ['sluggish', 'drowsy', 'listless'],
    example: 'He felt lethargic after staying up late.',
  },
  lucid: {
    partOfSpeech: 'adjective',
    definition: 'clear and easy to understand',
    synonyms: ['clear', 'intelligible', 'coherent'],
    example: 'The guide offered a lucid explanation.',
  },
  magnanimous: {
    partOfSpeech: 'adjective',
    definition: 'generous and forgiving, especially to a rival',
    synonyms: ['generous', 'noble', 'benevolent'],
    example: 'She was magnanimous in victory.',
  },
  malevolent: {
    partOfSpeech: 'adjective',
    definition: 'having or showing a wish to do harm',
    synonyms: ['malicious', 'spiteful', 'hostile'],
    example: 'The rumor had a malevolent intent.',
  },
  malleable: {
    partOfSpeech: 'adjective',
    definition: 'easily influenced or shaped',
    synonyms: ['flexible', 'adaptable', 'pliant'],
    example: 'Habits are malleable with consistent practice.',
  },
  maverick: {
    partOfSpeech: 'noun',
    definition: 'an independent-minded person',
    synonyms: ['nonconformist', 'individualist', 'rebel'],
    example: 'The maverick proposed a new approach.',
  },
  meticulous: {
    partOfSpeech: 'adjective',
    definition: 'showing great attention to detail',
    synonyms: ['careful', 'thorough', 'exact'],
    example: 'Her meticulous notes made revision easier.',
  },
  mitigate: {
    partOfSpeech: 'verb',
    definition: 'to make less severe or painful',
    synonyms: ['alleviate', 'reduce', 'ease'],
    example: 'Small breaks can mitigate fatigue.',
  },
  mundane: {
    partOfSpeech: 'adjective',
    definition: 'ordinary; lacking excitement',
    synonyms: ['ordinary', 'commonplace', 'routine'],
    example: 'He turned a mundane task into a game.',
  },
  nascent: {
    partOfSpeech: 'adjective',
    definition: 'just beginning to exist or develop',
    synonyms: ['emerging', 'incipient', 'developing'],
    example: 'The nascent idea needed refinement.',
  },
  nebulous: {
    partOfSpeech: 'adjective',
    definition: 'unclear; vague',
    synonyms: ['vague', 'hazy', 'indistinct'],
    example: 'The instructions were nebulous.',
  },
  nonchalant: {
    partOfSpeech: 'adjective',
    definition: 'calm and unconcerned',
    synonyms: ['casual', 'unconcerned', 'cool'],
    example: 'He appeared nonchalant, but he had prepared.',
  },
  nuanced: {
    partOfSpeech: 'adjective',
    definition: 'having subtle differences or distinctions',
    synonyms: ['subtle', 'refined', 'delicate'],
    example: 'A nuanced answer avoids extremes.',
  },
  obdurate: {
    partOfSpeech: 'adjective',
    definition: 'stubbornly refusing to change',
    synonyms: ['stubborn', 'unyielding', 'inflexible'],
    example: 'An obdurate stance slowed negotiations.',
  },
  obscure: {
    partOfSpeech: 'verb',
    definition: 'to make unclear or hard to understand',
    synonyms: ['hide', 'cloud', 'conceal'],
    example: 'Jargon can obscure the main point.',
  },
  obstinate: {
    partOfSpeech: 'adjective',
    definition: 'stubbornly refusing to change one’s opinion',
    synonyms: ['stubborn', 'unyielding', 'headstrong'],
    example: 'He stayed obstinate despite new evidence.',
  },
  ostensible: {
    partOfSpeech: 'adjective',
    definition: 'appearing true but not necessarily so',
    synonyms: ['apparent', 'seeming', 'professed'],
    example: 'The ostensible reason differed from the real one.',
  },
  paradox: {
    partOfSpeech: 'noun',
    definition: 'a seemingly contradictory statement that may be true',
    synonyms: ['contradiction', 'puzzle', 'enigma'],
    example: 'It is a paradox that more choice can reduce satisfaction.',
  },
  parsimonious: {
    partOfSpeech: 'adjective',
    definition: 'unwilling to spend; stingy',
    synonyms: ['stingy', 'miserly', 'frugal'],
    example: 'He was parsimonious with praise.',
  },
  perfunctory: {
    partOfSpeech: 'adjective',
    definition: 'done with little care or effort',
    synonyms: ['cursory', 'routine', 'mechanical'],
    example: 'A perfunctory review missed key issues.',
  },
  pervasive: {
    partOfSpeech: 'adjective',
    definition: 'spreading widely throughout an area',
    synonyms: ['widespread', 'common', 'prevalent'],
    example: 'A pervasive rumor affected morale.',
  },
  placate: {
    partOfSpeech: 'verb',
    definition: 'to calm or satisfy someone who is angry',
    synonyms: ['appease', 'pacify', 'soothe'],
    example: 'He tried to placate the upset customer.',
  },
  plausible: {
    partOfSpeech: 'adjective',
    definition: 'seeming reasonable or probable',
    synonyms: ['believable', 'credible', 'likely'],
    example: 'Her explanation was plausible.',
  },
  precarious: {
    partOfSpeech: 'adjective',
    definition: 'not securely held; risky or unstable',
    synonyms: ['unstable', 'risky', 'uncertain'],
    example: 'Their lead was precarious late in the game.',
  },
  precise: {
    partOfSpeech: 'adjective',
    definition: 'exact and accurate',
    synonyms: ['exact', 'accurate', 'specific'],
    example: 'Precise language improves clarity.',
  },
  preclude: {
    partOfSpeech: 'verb',
    definition: 'to prevent something from happening',
    synonyms: ['prevent', 'rule out', 'bar'],
    example: 'Time limits can preclude deep exploration.',
  },
  predispose: {
    partOfSpeech: 'verb',
    definition: 'to make someone likely to behave a certain way',
    synonyms: ['incline', 'make likely', 'dispose'],
    example: 'Stress can predispose you to mistakes.',
  },
  pragmatic: {
    partOfSpeech: 'adjective',
    definition: 'practical and focused on results',
    synonyms: ['practical', 'realistic', 'sensible'],
    example: 'A pragmatic plan targets the biggest weaknesses first.',
  },
  pristine: {
    partOfSpeech: 'adjective',
    definition: 'in its original, clean condition',
    synonyms: ['spotless', 'pure', 'unspoiled'],
    example: 'The dataset was not pristine and needed cleaning.',
  },
  prolific: {
    partOfSpeech: 'adjective',
    definition: 'producing many works or results',
    synonyms: ['productive', 'fruitful', 'abundant'],
    example: 'A prolific writer keeps a steady routine.',
  },
  prosaic: {
    partOfSpeech: 'adjective',
    definition: 'ordinary or unromantic; dull',
    synonyms: ['mundane', 'commonplace', 'plain'],
    example: 'The reason was prosaic but true.',
  },
  prudent: {
    partOfSpeech: 'adjective',
    definition: 'showing care and good judgment',
    synonyms: ['wise', 'sensible', 'judicious'],
    example: 'It is prudent to review mistakes the next day.',
  },
  pugnacious: {
    partOfSpeech: 'adjective',
    definition: 'eager to argue or fight',
    synonyms: ['combative', 'belligerent', 'quarrelsome'],
    example: 'His pugnacious style turned debates personal.',
  },
  quandary: {
    partOfSpeech: 'noun',
    definition: 'a state of uncertainty about what to do',
    synonyms: ['dilemma', 'predicament', 'puzzle'],
    example: 'She was in a quandary about which option to pick.',
  },
  quell: {
    partOfSpeech: 'verb',
    definition: 'to put an end to; suppress',
    synonyms: ['suppress', 'subdue', 'stifle'],
    example: 'A plan can quell pre-test nerves.',
  },
  rancor: {
    partOfSpeech: 'noun',
    definition: 'bitter resentment or hostility',
    synonyms: ['bitterness', 'resentment', 'spite'],
    example: 'Rancor made collaboration difficult.',
  },
  reconcile: {
    partOfSpeech: 'verb',
    definition: 'to restore friendly relations; make compatible',
    synonyms: ['resolve', 'settle', 'harmonize'],
    example: 'They reconciled their differing viewpoints.',
  },
  resolute: {
    partOfSpeech: 'adjective',
    definition: 'firmly determined',
    synonyms: ['steadfast', 'determined', 'unwavering'],
    example: 'She remained resolute despite setbacks.',
  },
  scrutinize: {
    partOfSpeech: 'verb',
    definition: 'to examine closely and critically',
    synonyms: ['inspect', 'analyze', 'study'],
    example: 'Scrutinize your errors to learn faster.',
  },
  salient: {
    partOfSpeech: 'adjective',
    definition: 'most noticeable or important',
    synonyms: ['notable', 'prominent', 'striking'],
    example: 'The salient point was buried in the last paragraph.',
  },
  sanguine: {
    partOfSpeech: 'adjective',
    definition: 'optimistic, especially in a difficult situation',
    synonyms: ['optimistic', 'hopeful', 'confident'],
    example: 'She stayed sanguine after a tough practice test.',
  },
  spurious: {
    partOfSpeech: 'adjective',
    definition: 'false; not genuine',
    synonyms: ['false', 'bogus', 'invalid'],
    example: 'The correlation was spurious.',
  },
  staunch: {
    partOfSpeech: 'adjective',
    definition: 'strongly loyal or committed',
    synonyms: ['steadfast', 'loyal', 'firm'],
    example: 'He was a staunch defender of the policy.',
  },
  superfluous: {
    partOfSpeech: 'adjective',
    definition: 'unnecessary; more than enough',
    synonyms: ['unnecessary', 'excess', 'redundant'],
    example: 'Cut superfluous words to sharpen the sentence.',
  },
  tenacious: {
    partOfSpeech: 'adjective',
    definition: 'holding firmly; persistent',
    synonyms: ['persistent', 'determined', 'dogged'],
    example: 'Tenacious effort pays off over time.',
  },
  tenuous: {
    partOfSpeech: 'adjective',
    definition: 'very weak or slight',
    synonyms: ['weak', 'fragile', 'flimsy'],
    example: 'The link between the events was tenuous.',
  },
  transient: {
    partOfSpeech: 'adjective',
    definition: 'temporary; lasting a short time',
    synonyms: ['temporary', 'brief', 'fleeting'],
    example: 'A transient setback does not define the semester.',
  },
  ubiquitous: {
    partOfSpeech: 'adjective',
    definition: 'present everywhere',
    synonyms: ['omnipresent', 'widespread', 'universal'],
    example: 'Smartphones are ubiquitous on campuses.',
  },
  venerate: {
    partOfSpeech: 'verb',
    definition: 'to regard with deep respect',
    synonyms: ['revere', 'honor', 'esteem'],
    example: 'Many venerate teachers who changed their lives.',
  },
  veracity: {
    partOfSpeech: 'noun',
    definition: 'truthfulness; accuracy',
    synonyms: ['truth', 'honesty', 'accuracy'],
    example: 'The veracity of the claim was questioned.',
  },
  vociferous: {
    partOfSpeech: 'adjective',
    definition: 'loud and forceful in expressing opinions',
    synonyms: ['outspoken', 'vehement', 'boisterous'],
    example: 'The vociferous debate filled the hall.',
  },
  wary: {
    partOfSpeech: 'adjective',
    definition: 'careful and watchful about danger',
    synonyms: ['cautious', 'guarded', 'alert'],
    example: 'Be wary of shortcuts that skip understanding.',
  },
  zealous: {
    partOfSpeech: 'adjective',
    definition: 'showing great enthusiasm or passion',
    synonyms: ['eager', 'ardent', 'fervent'],
    example: 'A zealous effort can accelerate improvement.',
  },
  abstruse: {
    partOfSpeech: 'adjective',
    definition: 'difficult to understand; obscure',
    synonyms: ['obscure', 'complex', 'esoteric'],
    example: 'The passage was abstruse without context.',
  },
  acquiesce: {
    partOfSpeech: 'verb',
    definition: 'to accept something reluctantly without protest',
    synonyms: ['comply', 'consent', 'yield'],
    example: 'He acquiesced to the new deadline.',
  },
  acrimonious: {
    partOfSpeech: 'adjective',
    definition: 'bitter and sharp in tone',
    synonyms: ['bitter', 'caustic', 'hostile'],
    example: 'The discussion became acrimonious quickly.',
  },
  adulation: {
    partOfSpeech: 'noun',
    definition: 'excessive praise or admiration',
    synonyms: ['praise', 'worship', 'flattery'],
    example: 'The celebrity received constant adulation.',
  },
  aggrandize: {
    partOfSpeech: 'verb',
    definition: 'to increase power, status, or wealth',
    synonyms: ['enhance', 'increase', 'magnify'],
    example: 'He tried to aggrandize his role in the project.',
  },
  altruism: {
    partOfSpeech: 'noun',
    definition: 'selfless concern for others',
    synonyms: ['selflessness', 'generosity', 'benevolence'],
    example: 'Altruism motivated her volunteer work.',
  },
  anachronism: {
    partOfSpeech: 'noun',
    definition: 'something out of its proper time period',
    synonyms: ['misplacement', 'oddity', 'throwback'],
    example: 'The reference felt like an anachronism.',
  },
  apocryphal: {
    partOfSpeech: 'adjective',
    definition: 'of doubtful authenticity; probably false',
    synonyms: ['dubious', 'questionable', 'unverified'],
    example: 'The story is likely apocryphal.',
  },
  ardent: {
    partOfSpeech: 'adjective',
    definition: 'passionate; intensely devoted',
    synonyms: ['fervent', 'zealous', 'enthusiastic'],
    example: 'He was an ardent supporter of the team.',
  },
  assuage: {
    partOfSpeech: 'verb',
    definition: 'to relieve or make less severe',
    synonyms: ['ease', 'alleviate', 'mitigate'],
    example: 'A clear plan can assuage anxiety.',
  },
  attenuate: {
    partOfSpeech: 'verb',
    definition: 'to weaken or reduce in force',
    synonyms: ['reduce', 'diminish', 'lessen'],
    example: 'Earplugs can attenuate background noise.',
  },
  audacious: {
    partOfSpeech: 'adjective',
    definition: 'bold; daring; reckless',
    synonyms: ['bold', 'daring', 'fearless'],
    example: 'She made an audacious attempt at the hardest problem.',
  },
  augment: {
    partOfSpeech: 'verb',
    definition: 'to increase; make larger',
    synonyms: ['increase', 'expand', 'enhance'],
    example: 'He augmented his notes with extra examples.',
  },
  avuncular: {
    partOfSpeech: 'adjective',
    definition: 'kind and friendly toward a younger person',
    synonyms: ['fatherly', 'benevolent', 'kindly'],
    example: 'The mentor offered avuncular advice.',
  },
  bolster: {
    partOfSpeech: 'verb',
    definition: 'to support or strengthen',
    synonyms: ['support', 'strengthen', 'reinforce'],
    example: 'Extra practice can bolster confidence.',
  },
  brazen: {
    partOfSpeech: 'adjective',
    definition: 'bold and shameless',
    synonyms: ['shameless', 'bold', 'impudent'],
    example: 'It was a brazen attempt to cheat.',
  },
  brusque: {
    partOfSpeech: 'adjective',
    definition: 'abrupt and curt in manner',
    synonyms: ['curt', 'blunt', 'terse'],
    example: 'His brusque reply sounded harsher than intended.',
  },
  candid: {
    partOfSpeech: 'adjective',
    definition: 'truthful and straightforward',
    synonyms: ['frank', 'open', 'direct'],
    example: 'She gave a candid assessment of her progress.',
  },
  clandestine: {
    partOfSpeech: 'adjective',
    definition: 'kept secret or done secretly',
    synonyms: ['secret', 'covert', 'surreptitious'],
    example: 'They held a clandestine meeting.',
  },
  conundrum: {
    partOfSpeech: 'noun',
    definition: 'a confusing and difficult problem',
    synonyms: ['puzzle', 'dilemma', 'riddle'],
    example: 'Balancing work and study can be a conundrum.',
  },
  credulous: {
    partOfSpeech: 'adjective',
    definition: 'too ready to believe; gullible',
    synonyms: ['gullible', 'naive', 'trusting'],
    example: 'A credulous reader may accept weak sources.',
  },
  decorum: {
    partOfSpeech: 'noun',
    definition: 'proper behavior and manners',
    synonyms: ['propriety', 'politeness', 'etiquette'],
    example: 'Decorum kept the debate respectful.',
  },
  defiant: {
    partOfSpeech: 'adjective',
    definition: 'openly resisting authority or challenges',
    synonyms: ['rebellious', 'resistant', 'bold'],
    example: 'She took a defiant stance against the rule.',
  },
  didactic: {
    partOfSpeech: 'adjective',
    definition: 'intended to teach, sometimes moralizing',
    synonyms: ['instructional', 'educational', 'pedagogical'],
    example: 'The book had a didactic tone.',
  },
  diffident: {
    partOfSpeech: 'adjective',
    definition: 'shy; lacking confidence',
    synonyms: ['shy', 'timid', 'reserved'],
    example: 'He seemed diffident during the presentation.',
  },
  dissonance: {
    partOfSpeech: 'noun',
    definition: 'lack of harmony; tension between ideas',
    synonyms: ['discord', 'conflict', 'tension'],
    example: 'There was dissonance between the claims and the data.',
  },
  docile: {
    partOfSpeech: 'adjective',
    definition: 'easy to manage; obedient',
    synonyms: ['obedient', 'compliant', 'tractable'],
    example: 'The docile animal followed calmly.',
  },
  duplicity: {
    partOfSpeech: 'noun',
    definition: 'deceitfulness; double-dealing',
    synonyms: ['deceit', 'dishonesty', 'treachery'],
    example: 'Her duplicity was revealed in the emails.',
  },
  egregious: {
    partOfSpeech: 'adjective',
    definition: 'outstandingly bad; shocking',
    synonyms: ['shocking', 'flagrant', 'outrageous'],
    example: 'It was an egregious error in the final draft.',
  },
  enmity: {
    partOfSpeech: 'noun',
    definition: 'deep hostility or hatred',
    synonyms: ['hostility', 'hatred', 'antipathy'],
    example: 'Old enmity resurfaced during the dispute.',
  },
  erratic: {
    partOfSpeech: 'adjective',
    definition: 'unpredictable; irregular',
    synonyms: ['unpredictable', 'inconsistent', 'irregular'],
    example: 'An erratic schedule makes habits hard to build.',
  },
  esoteric: {
    partOfSpeech: 'adjective',
    definition: 'understood by only a small group',
    synonyms: ['obscure', 'arcane', 'abstruse'],
    example: 'The text used esoteric terminology.',
  },
  fallacious: {
    partOfSpeech: 'adjective',
    definition: 'based on a mistaken belief; logically flawed',
    synonyms: ['false', 'invalid', 'unsound'],
    example: 'The argument was fallacious.',
  },
  galvanize: {
    partOfSpeech: 'verb',
    definition: 'to shock or excite into action',
    synonyms: ['motivate', 'spur', 'stimulate'],
    example: 'The goal galvanized the team.',
  },
  harangue: {
    partOfSpeech: 'noun',
    definition: 'a long, aggressive speech',
    synonyms: ['tirade', 'rant', 'lecture'],
    example: 'The coach delivered a harangue at halftime.',
  },
  haughty: {
    partOfSpeech: 'adjective',
    definition: 'arrogantly superior and disdainful',
    synonyms: ['arrogant', 'proud', 'snobbish'],
    example: 'His haughty tone annoyed the class.',
  },
  impetuous: {
    partOfSpeech: 'adjective',
    definition: 'acting quickly without thought',
    synonyms: ['rash', 'impulsive', 'hasty'],
    example: 'An impetuous answer can cost points.',
  },
  impugn: {
    partOfSpeech: 'verb',
    definition: 'to call into question; challenge as false',
    synonyms: ['challenge', 'question', 'dispute'],
    example: 'They impugned her credibility without proof.',
  },
  intransigent: {
    partOfSpeech: 'adjective',
    definition: 'unwilling to change one’s views',
    synonyms: ['unyielding', 'inflexible', 'obdurate'],
    example: 'An intransigent attitude blocked compromise.',
  },
  irascible: {
    partOfSpeech: 'adjective',
    definition: 'easily angered',
    synonyms: ['irritable', 'hot-tempered', 'testy'],
    example: 'He grew irascible under stress.',
  },
  malaise: {
    partOfSpeech: 'noun',
    definition: 'a general feeling of discomfort or unease',
    synonyms: ['unease', 'discomfort', 'illness'],
    example: 'A vague malaise made it hard to focus.',
  },
  mendacious: {
    partOfSpeech: 'adjective',
    definition: 'not telling the truth; lying',
    synonyms: ['dishonest', 'lying', 'deceitful'],
    example: 'The mendacious claim was easy to refute.',
  },
  mollify: {
    partOfSpeech: 'verb',
    definition: 'to calm or soothe',
    synonyms: ['soothe', 'appease', 'placate'],
    example: 'He tried to mollify the upset group.',
  },
  nefarious: {
    partOfSpeech: 'adjective',
    definition: 'wicked or criminal',
    synonyms: ['wicked', 'villainous', 'evil'],
    example: 'The plan had a nefarious purpose.',
  },
  opulent: {
    partOfSpeech: 'adjective',
    definition: 'rich and luxurious',
    synonyms: ['luxurious', 'sumptuous', 'lavish'],
    example: 'The opulent room felt like a museum.',
  },
  panacea: {
    partOfSpeech: 'noun',
    definition: 'a remedy for all problems',
    synonyms: ['cure-all', 'solution', 'remedy'],
    example: 'There is no panacea for procrastination.',
  },
  pedantic: {
    partOfSpeech: 'adjective',
    definition: 'overly concerned with minor details',
    synonyms: ['overly detailed', 'nitpicky', 'scholarly'],
    example: 'His pedantic comments slowed the meeting.',
  },
  platitude: {
    partOfSpeech: 'noun',
    definition: 'a dull or overused remark',
    synonyms: ['cliche', 'banality', 'truism'],
    example: 'The speech was full of platitudes.',
  },
  prodigal: {
    partOfSpeech: 'adjective',
    definition: 'wastefully extravagant',
    synonyms: ['wasteful', 'reckless', 'extravagant'],
    example: 'He was prodigal with time during the week.',
  },
  propensity: {
    partOfSpeech: 'noun',
    definition: 'a natural tendency to behave in a certain way',
    synonyms: ['tendency', 'inclination', 'likelihood'],
    example: 'She has a propensity to overthink.',
  },
  quixotic: {
    partOfSpeech: 'adjective',
    definition: 'extremely idealistic; unrealistic',
    synonyms: ['idealistic', 'impractical', 'romantic'],
    example: 'It was a quixotic plan without resources.',
  },
  recalcitrant: {
    partOfSpeech: 'adjective',
    definition: 'stubbornly resisting authority or control',
    synonyms: ['uncooperative', 'defiant', 'obstinate'],
    example: 'The recalcitrant student refused to participate.',
  },
  relegate: {
    partOfSpeech: 'verb',
    definition: 'to assign to a lower rank or lesser place',
    synonyms: ['downgrade', 'assign', 'defer'],
    example: 'He relegated the task to the end of the list.',
  },
  sporadic: {
    partOfSpeech: 'adjective',
    definition: 'occurring irregularly',
    synonyms: ['irregular', 'infrequent', 'scattered'],
    example: 'Sporadic study makes retention harder.',
  },
  stipulate: {
    partOfSpeech: 'verb',
    definition: 'to specify as a condition',
    synonyms: ['specify', 'require', 'state'],
    example: 'The contract stipulated a strict deadline.',
  },
  succinct: {
    partOfSpeech: 'adjective',
    definition: 'brief and clearly expressed',
    synonyms: ['concise', 'terse', 'compact'],
    example: 'Give a succinct explanation in two sentences.',
  },
  taciturn: {
    partOfSpeech: 'adjective',
    definition: 'reserved; not talkative',
    synonyms: ['silent', 'reticent', 'laconic'],
    example: 'He was taciturn during the interview.',
  },
  trenchant: {
    partOfSpeech: 'adjective',
    definition: 'sharp, clear, and effective',
    synonyms: ['incisive', 'keen', 'piercing'],
    example: 'Her trenchant critique improved the essay.',
  },
  vacillate: {
    partOfSpeech: 'verb',
    definition: 'to waver between options',
    synonyms: ['waver', 'hesitate', 'fluctuate'],
    example: 'Do not vacillate; pick a plan and execute.',
  },
  vilify: {
    partOfSpeech: 'verb',
    definition: 'to speak about as evil or bad',
    synonyms: ['denounce', 'defame', 'slander'],
    example: 'He tried to vilify his opponent.',
  },
  vindicate: {
    partOfSpeech: 'verb',
    definition: 'to clear from blame; justify',
    synonyms: ['justify', 'exonerate', 'clear'],
    example: 'The results vindicated her approach.',
  },
  visceral: {
    partOfSpeech: 'adjective',
    definition: 'felt deeply; instinctive',
    synonyms: ['instinctive', 'deep', 'gut'],
    example: 'He had a visceral reaction to the news.',
  },
  articulate: {
    partOfSpeech: 'adjective',
    definition: 'able to express ideas clearly and effectively',
    synonyms: ['eloquent', 'clear', 'expressive'],
    example: 'She gave an articulate explanation of the concept.',
  },
  clarify: {
    partOfSpeech: 'verb',
    definition: 'to make something easier to understand',
    synonyms: ['explain', 'illuminate', 'make clear'],
    example: 'She clarified the instructions for the group.',
  },
  deliberate: {
    partOfSpeech: 'adjective',
    definition: 'done intentionally and thoughtfully',
    synonyms: ['intentional', 'purposeful', 'careful'],
    example: 'He made a deliberate choice to practice daily.',
  },
  empathize: {
    partOfSpeech: 'verb',
    definition: 'to understand and share the feelings of another',
    synonyms: ['relate', 'understand', 'identify'],
    example: 'She tried to empathize with a frustrated teammate.',
  },
  collaborate: {
    partOfSpeech: 'verb',
    definition: 'to work together toward a shared goal',
    synonyms: ['cooperate', 'team up', 'work together'],
    example: 'They collaborated to finish the presentation.',
  },
  contextualize: {
    partOfSpeech: 'verb',
    definition: 'to place something in context for better understanding',
    synonyms: ['frame', 'situate', 'explain'],
    example: 'He contextualized the quote with historical background.',
  },
  diplomatic: {
    partOfSpeech: 'adjective',
    definition: 'tactful in dealing with people and situations',
    synonyms: ['tactful', 'politic', 'careful'],
    example: 'She gave diplomatic feedback during the review.',
  },
  negotiate: {
    partOfSpeech: 'verb',
    definition: 'to discuss to reach an agreement',
    synonyms: ['bargain', 'discuss', 'arrange'],
    example: 'They negotiated a new deadline.',
  },
  persuade: {
    partOfSpeech: 'verb',
    definition: 'to convince someone to do or believe something',
    synonyms: ['convince', 'influence', 'sway'],
    example: 'He persuaded the group with a clear rationale.',
  },
  reiterate: {
    partOfSpeech: 'verb',
    definition: 'to say or do again for emphasis',
    synonyms: ['repeat', 'restate', 'emphasize'],
    example: 'She reiterated the main point at the end.',
  },
  synthesize: {
    partOfSpeech: 'verb',
    definition: 'to combine ideas into a whole',
    synonyms: ['combine', 'integrate', 'merge'],
    example: 'She synthesized the research into one narrative.',
  },
};

const WORDS = Object.keys(MEANINGS);

export const WORD_BANK: CoefficientWord[] = WORDS.map((word) => {
  const meaning = MEANINGS[word];
  return {
    id: word,
    word,
    phonetic: meaning.phonetic ?? '',
    partOfSpeech: meaning.partOfSpeech,
    definition: meaning.definition,
    synonyms: meaning.synonyms ?? [],
    example: meaning.example ?? '',
  };
});
